#
# Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

name: 'Run tests'

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      bootjdk-platform:
        required: true
        type: string
      runs-on:
        required: true
        type: string

env:
  # These are needed to make the MSYS2 bash work properly
  MSYS2_PATH_TYPE: minimal
  CHERE_INVOKING: 1

jobs:
  test:
    name: test
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        test-name:
          - 'jdk/tier1 part 1'
          - 'jdk/tier1 part 2'
          - 'jdk/tier1 part 3'
          - 'langtools/tier1'
          - 'hs/tier1 common'
          - 'hs/tier1 compiler'
          - 'hs/tier1 gc'
          - 'hs/tier1 runtime'
          - 'hs/tier1 serviceability'

        include:
          - test-name: 'jdk/tier1 part 1'
            test-suite: 'test/jdk/:tier1_part1'

          - test-name: 'jdk/tier1 part 2'
            test-suite: 'test/jdk/:tier1_part2'

          - test-name: 'jdk/tier1 part 3'
            test-suite: 'test/jdk/:tier1_part3'

          - test-name: 'langtools/tier1'
            test-suite: 'test/langtools/:tier1'

          - test-name: 'hs/tier1 common'
            test-suite: 'test/hotspot/jtreg/:tier1_common'
            debug-suffix: -debug

          - test-name: 'hs/tier1 compiler'
            test-suite: 'test/hotspot/jtreg/:tier1_compiler'
            debug-suffix: -debug

          - test-name: 'hs/tier1 gc'
            test-suite: 'test/hotspot/jtreg/:tier1_gc'
            debug-suffix: -debug

          - test-name: 'hs/tier1 runtime'
            test-suite: 'test/hotspot/jtreg/:tier1_runtime'
            debug-suffix: -debug

          - test-name: 'hs/tier1 serviceability'
            test-suite: 'test/hotspot/jtreg/:tier1_serviceability'
            debug-suffix: -debug

    steps:
     - run: echo "Hi"
